### ISSUE TITLE
Удалить из проекта for

### ISSUE THREAD

**Issue by Sha1fei** [KatePronina/Slider#10]
![Снимок экрана от 2019-08-26 16-05-24](https://user-images.githubusercontent.com/31854808/63679421-768af080-c81b-11e9-86c0-666604b9b574.png)

**Comment by KatePronina** [comment]
Там, где `for` используется не для итерации по массиву (как на скрине выше), тоже убрать?

**Comment by Sha1fei** [comment]
Да, необходимо везде убрать)

**Comment by KatePronina** [comment]
Пока не придумала, как можно переписать код на скрине без цикла, мне же надо динамически сгенерировать все возможные значения для шкалы
Чем плохо решение с циклом?

**Comment by Sha1fei** [comment]
![Screenshot 2019-09-24 at 12 13 28](https://user-images.githubusercontent.com/31854808/65482938-c6191680-dec4-11e9-9a67-c4e04ba21800.png)
Можно к примеру так сделать. Цикл плох, что он просто перебирает значения, и ничего не возвращает. Т.е. чтобы получить values тебе изнутри цикла приходится пушить в него значения, мутируя массив, а не создавая новый.

**Comment by KatePronina** [comment]
Аааа, окей, поняла, спасибо)
