### ISSUE TITLE
UI

### ISSUE THREAD

**Issue by Sha1fei** [KatePronina/Slider#12]
Тут лучше убрать логику с z-index - пусть они не дают возможность заезжать друг на друга. И не придется лезть в стили инлайново)
![Снимок экрана от 2019-08-26 16-10-21](https://user-images.githubusercontent.com/31854808/63679787-5c9ddd80-c81c-11e9-88fc-13c094487113.png)

**Comment by KatePronina** [comment]
Пока убрала инлайновые стили, но про 

> пусть они не дают возможность заезжать друг на друга

немного не поняла, как это должно работать, ведь если минимальное и максимальное значения будут равны, то оба поинта должны быть на одном месте или как?)

**Comment by Sha1fei** [comment]
Рэнж подразумевает выдачу какого-либо диапазона (хотя бы один минимальный шаг) такой ситуации по идеи не должно произойти когда они равны) Но в целом я не против твоего решения, если хочешь то можно оставить его реализацию, просто придется больше рефакторить логики по итогу.

**Comment by Sha1fei** [comment]
Можно использовать и твой вариант, но разрулить это не через инлайновые стили, а добавлением последнему передвигаемому ползунку модификатор, который будет увеличивать его z-index.

**Comment by KatePronina** [comment]
Так сейчас же оно так и работает, разве нет?) В коммите выше как раз исправила

> добавлением последнему передвигаемому ползунку модификатор, который будет увеличивать его z-index

**Comment by Sha1fei** [comment]
Да, ты права) Только забывай про именование модификаторов,  active => actived, disbale => disabled, vertical => direction_vertical)
