### ISSUE TITLE
Ограничение размеров

### ISSUE THREAD

**Issue by Sha1fei** [KatePronina/Slider#19]
Тут лучше не задавать ограничение в размерах, пусть лучше ограничивается родителем, чтобы можно было адаптировать под свои нужды)

**Comment by Sha1fei** [comment]
![Снимок экрана от 2019-08-26 16-52-14](https://user-images.githubusercontent.com/31854808/63682535-5874be80-c822-11e9-981d-6789a7ca67b5.png)

**Comment by KatePronina** [comment]
Пока убрала блок configuration из вертикальных слайдеров на демо-странице, т.к. сейчас configuration добавляется в один элемент вместе со слайдером, что я исправлю при вынесении configuration из слайдера в ишью про архитектуру
