### ISSUE TITLE
Архитектура приложения

### ISSUE THREAD

**Issue by Sha1fei** [KatePronina/Slider#2]
Сейчас у тебя модель и вьюха знают о друг друге. Контроллер же не влияет на то, какие методы следует вызывать при различных событиях.  Для того чтобы ослабить зависимости, можно воспользоваться паттерном Observer.

**Comment by Sha1fei** [comment]
Поскольку это плагин, то у тебя должно быть минимум две независимые вьюхи, первая должна отвечать за отрисовку самого слайдера, вторая для инпутов, которые у тебя в рамке на демо страничке. Сейчас ты харкодишь их в общей вьюхе, и вьюха с инпуами является неотъемлимой частью твоего приложения, хотя таковой она не должна быть (в повседневном использовании при вызове плагина, должен отрисовываться только сладйер). Можно отделить эту часть путем инициализации вью с инпутами вне слайдера, и передачи объекта в качестве 
опционального параметра плагину. (см файл demo.js, кстати он как раз и должен называться app.ts).

**Comment by Sha1fei** [comment]
Сейчас во вью и модели нарушены зоны ответственности. У тебя из вью прилетает конкретное значение которое у себя должны установить модель(хотя должно быть наоборот). Тут следует реализовать отличную логику: Вью должна знать размеры слайдера, фиксировать смещение тултипа, и оповещать контроллер с передачей относительной величины (длина слайдера / длину смещения от его края тултипа ). При расчете модель будет использовать эту относительную величину для расчета новой позиции при достижении границы смещения на новое положение(с учетом диапазона и шага слайдера) и отдавать ее вьюхе для отрисовки посредством контроллера.  Для конвертации во вью можно предусмотреть отдельный класс.

**Comment by Sha1fei** [comment]
Также стоит обратить внимание на то что логика для подписки будет переиспользуемой, и стоит сразу задуматься о выделении ее в отдельный уровень абстракции.

**Comment by Sha1fei** [comment]
Внесу небольшие поправки, предлагаю использовать класс App как дополнительный уровень абстракции в котором будет происходить инициализация контроллера(внутри которого ты сейчас инициализруешь модель и вьюху сладйера) плюс реализации методов для подписок и оповещений (в контролере и вьюхе с инпутами, тоже должна иметься реализация методов подписок и оповещений для общения с App).

**Comment by Sha1fei** [comment]
По поводу модели сразу стоит обратить внимание на количество публичных методов, их должно быть минимальное количество, метод для подписки на оповещения модели и метод для установки новых значений (было бы отлично если он принимал бы не отдельные значения к примеру, а объект из всех возможных значений для слайдера, часть из которых может быть и не будет использовано для расчетов, к примеру если используется только один ползунок), это было бы удобно поскольку модели было бы все равно откуда прилетели данные из вьюхи слайдера или из вьюхи панели управления.

**Comment by Sha1fei** [comment]
Отпишись плиз как закончишь с рефакторингом архитектуры, чтобы было понятно когда смотреть)

**Comment by Sha1fei** [comment]
В сети есть интересная книжка Стефан Стоянов JavaScript. Шаблоны. Он разбирает паттерн наблюдатель, как реализуется подписка и отписка на события. Всю книгу читать не стоит, можно ток главу про реализацию этого паттерна. Если возникнут вопросы, можем тут обсудить после)

**Comment by KatePronina** [comment]
Ок, отпишусь) Я просто делаю каждую часть ишью отдельно, чтобы не мешать все в кучу
Да, я помню про наблюдатель, я прочитаю и сделаю
Спасибо за рекомендацию)

**Comment by KatePronina** [comment]
Переделала архитектуру, можно смотреть)
Для передачи данных от плагина до вью с инпутами использовала генерацию событий плагином
Для передачи данных от вью с инпутами до плагина использовала публичные методы плагина
Т.е. плагин предоставляет методы и события для обмена данными, а вью с инпутами вызывает нужные методы и слушает нужные события
Получается, что для вью с инпутами не нужен Observer, т.к. плагин предоставляет API, и вью с инпутами и так независима от плагина

**Comment by Sha1fei** [comment]
Нужно подправить следующие места: 1) Модель и Вью сейчас подписываются друг на друга в контроллере, хотя такого не должно быть. Контроллер должен подписываться на события Модели и Вьюхи, и дергать необходимые методы. 2)Сокращай не нужные методы, к примеру у модели должно остаться 2 публичных метода один наследуемый от обсервера для подписки, и второй для передачи данных, и у вьюх аналогично, многие лишние методы уйдут 3) Данные модели должны быть приватными. 4) Решение с возвратом объектра из плагина подходит, но тут тоже можно обойтись двумя методами(подписка, и метод Application для передачи данных)

**Comment by Sha1fei** [comment]
Смотри, твои публичные методы модели должны выглядеть примерно так
![Screenshot 2019-09-27 at 12 34 52](https://user-images.githubusercontent.com/31854808/65744661-38873200-e123-11e9-9b1b-1e9b25c5913e.png)
Контроллер, который подписан на оповещение может сам определять, какие параметры выдернуть из передаваемого объекта, и отдать их вьюхе слайдера, а какие оповестить  application, о новом состоянии инпутов, чтобы он оповестил вьюху с инпутами. Аналогично и в обратную сторону вьюха передает параметры которые ей доступны, контроллер у себя подтягивает текущий стэйт модели, перезаписывает в нем переданные поля и передает их модели на валидацию.

**Comment by Sha1fei** [comment]
Поле private positionLength: number | number[], можно поменять тип на number | number[] | null, и в дефолтных параметрах задать null.

**Comment by KatePronina** [comment]
> Аналогично и в обратную сторону вьюха передает параметры которые ей доступны, контроллер у себя подтягивает текущий стэйт модели, перезаписывает в нем переданные поля и передает их модели на валидацию.

Было исправлено в этом коммите 3855e3d

**Comment by Sha1fei** [comment]
Для чего в модели остался вот этот метод?
![Снимок экрана от 2019-10-01 08-14-47](https://user-images.githubusercontent.com/31854808/65927359-a84b3480-e423-11e9-99ca-4f0f3bfd9033.png)

**Comment by Sha1fei** [comment]
Метод validateState должен возвращать полностью отвалидрованный объект который присваивается стэйту, для чего нужен вот это код?
![Снимок экрана от 2019-10-01 08-36-44](https://user-images.githubusercontent.com/31854808/65928073-a171f100-e426-11e9-9f62-0b38a231e296.png)

**Comment by Sha1fei** [comment]
Это проверка должна быть внутри метода validateValue
![Снимок экрана от 2019-10-01 08-38-26](https://user-images.githubusercontent.com/31854808/65928130-db42f780-e426-11e9-9983-88985b91a5c1.png)

**Comment by Sha1fei** [comment]
Вот так можно сократить запись
![Снимок экрана от 2019-10-01 08-40-09](https://user-images.githubusercontent.com/31854808/65928202-24934700-e427-11e9-98f4-37b9d500cd45.png)
По факту в методе validateState, должны вызываться валидации всех параметров, если к примеру для валидации value в методе validateValue нужны отвалидированные параметры maxValue minValue step, то их тоже передавай в это метод.

**Comment by KatePronina** [comment]
> Для чего в модели остался вот этот метод?
> ![Снимок экрана от 2019-10-01 08-14-47](https://user-images.githubusercontent.com/31854808/65927359-a84b3480-e423-11e9-99ca-4f0f3bfd9033.png)

Чтобы модель при перемещении ползунка вызывала событие, которое не перерисовывает слайдер (как в случае с методом модели onNewState - вызывается событие onSetState, на которое контроллер вызывает перерисовку), а просто перемещает ползунок (вызывается событие onSetValue, и контроллер вызовет перемещение ползунка)

**Comment by Sha1fei** [comment]
У тебя есть контроллер в котором это все можно реализовать) У модели остается  только метод onNewState (именование методов обсудим позже пока пусть так останется) Это метод принимает либо новое состояние от  вьюхи с инпутами(промежуточные слои опустим)  и флаг представляемый контроллером, либо текущее состояние модели (его предоставляет метод getSettings, вызываем его в контроллере) с перезаписанным свойством value его предоставляет вьюха слайдер и флаг представляемый контроллером. События на которые подписывается контроллер с вызовом метода `onNewState` модели можно назвать `"settingsUpdated"` и `"valueUpdated"`.  Далее когда модель оповещает что ее состояние изменилось, на событие `"stateUpdated"`  подписан один метод контроллера, который внутри вызывает метод вьюхи сладера и передает туда один параметр и оповещает  вьюху с ипутами, передавая весь объект сеттингов. Для того чтобы запускать процесс отрисовки смещения ползунка слайдера, а не перерисовки самого слайдера (когда к примеру изменились minValue и maxValue), предлагаю ввести в интерфейс `IFullSettings` булевый флаг  wasVendorsSettingUpdated(о нем писал выше). В это поле вьюха слайдера будет записывать false, а вьюха инпутов  true(тут стоит оговорится, что это делают не сами вьюхи а методы контроллера которые подписаны на события вьюх). Следовательно когда будет вызываться метод `updateSettings` подписанный на событие модели `"stateUpdated"` внутри по этому флагу можно будет либо запускать метод изменения позиции ползунка  `this.view.onChangedValue(value, newPositionLength);` либо полную перерисовку `this.view.remove();  this.view.initSlider(settings);`, а также метод 
```
this.publish('onNewSettings', {
      ...settings,
      positionLength: null,
    });
```
для обоих случаев)

**Comment by Sha1fei** [comment]
Эти преобразования позволят оставить у модели одну точку входа и выхода, уменьшить количество логики и оптимизировать методы валидации параметров состояния модели, а также сохранить текущие интрефейсы вьюх)

**Comment by KatePronina** [comment]
Вместо булевого флага использовала строки с названиями событий, чтобы была возможность добавления новых разграничений, а не только двух (true/false)

**Comment by Sha1fei** [comment]
Модель не должна ничего знать о доме 
![Screenshot 2019-10-07 at 09 13 58](https://user-images.githubusercontent.com/31854808/66280875-ee503e80-e8e2-11e9-8e78-a140fb7a818e.png)

**Comment by Sha1fei** [comment]
Удали из модели не используемые методы
![Screenshot 2019-10-07 at 09 16 04](https://user-images.githubusercontent.com/31854808/66280910-222b6400-e8e3-11e9-96a0-a73388e716d8.png)

**Comment by Sha1fei** [comment]
Почему countValue находится не внутри  validateValue?
![Screenshot 2019-10-07 at 10 23 36](https://user-images.githubusercontent.com/31854808/66283168-a59d8300-e8ec-11e9-81dd-800e7775f40c.png)

**Comment by Sha1fei** [comment]
Имеются методы над которыми стоит подумать как их назвать: у тебя три метода которые отвечают за валидацию интервала значений, такого не должно быть, оставь один, пусть он целиком отвечает за валидацию, чтобы уменьшить количество кода в нем, выноси логику с расчетами в отдельные методы(их именование не должны содержать параметры с которыми они работают, по факту именование должно описывать обезличенный функционал возложенный на них)
![Screenshot 2019-10-07 at 10 27 34](https://user-images.githubusercontent.com/31854808/66283302-3c6a3f80-e8ed-11e9-9299-ee8001413c05.png)
![Screenshot 2019-10-07 at 10 27 40](https://user-images.githubusercontent.com/31854808/66283309-42602080-e8ed-11e9-9f1c-8456d86d1f01.png)
![Screenshot 2019-10-07 at 10 27 54](https://user-images.githubusercontent.com/31854808/66283310-42602080-e8ed-11e9-84aa-b6e6d4dab3c5.png)
checkedValue - нужно придумать более уточняющие название
посмотри в стандартах как именуются методы которые возвращают boolean
![Screenshot 2019-10-07 at 10 52 02](https://user-images.githubusercontent.com/31854808/66284126-a33d2800-e8f0-11e9-9ea6-4ac9fbc197c0.png)
Для чего ты сделал это метод статичным? 
![Screenshot 2019-10-07 at 10 54 34](https://user-images.githubusercontent.com/31854808/66284185-e5ff0000-e8f0-11e9-9457-1f22943b9fe3.png)
Это нужно переписать, мы не используем валидацию  по булевому значению.
![Screenshot 2019-10-07 at 10 58 19](https://user-images.githubusercontent.com/31854808/66284398-b69cc300-e8f1-11e9-9fe3-7ebfc433b27a.png)
![Screenshot 2019-10-07 at 10 58 01](https://user-images.githubusercontent.com/31854808/66284405-bd2b3a80-e8f1-11e9-8a7e-d63a446cb179.png)

**Comment by Sha1fei** [comment]
Если будут вопросы по именованиям, либо по реализации задавай их сразу, чтобы потом не переписывать) В целом по модели не так много замечаний осталось, остальные классы должны пойти быстрее)

**Comment by KatePronina** [comment]
> Для чего ты сделал это метод статичным?

Когда в проекте использовался eslint с настройками для ts, линтер ругался на этот метод, потому что в нем не используется ничего из this

**Comment by KatePronina** [comment]
> Это нужно переписать, мы не используем валидацию по булевому значению.

**Comment by KatePronina** [comment]
> Это нужно переписать, мы не используем валидацию по булевому значению.
Почему?

**Comment by KatePronina** [comment]
> Это нужно переписать, мы не используем валидацию по булевому значению.

Почему?

**Comment by Sha1fei** [comment]
Переименуй методы createPositionLength => validatePositionOffsets,  countPositionLength => countPositionOffsets,       validateIntervalValue =>  validateIntervalValues, добавить метод validateSingleValue, validateValue => validateValues, checkValue => validateSingleBoundaryValues, adjustValuesToStartAndEnd => validateIntervalBoundaryValues (проверка кравых условий должна выолняться внутри валидации интервала и значения соответсвенно), onNewState => dispatchState, getSettings=> getState Для чего нужны вот эти проверки?
![Screenshot 2019-10-09 at 11 51 26](https://user-images.githubusercontent.com/31854808/66452560-2abe9e80-ea8b-11e9-9d05-be034b783a0b.png)
![Screenshot 2019-10-09 at 11 51 21](https://user-images.githubusercontent.com/31854808/66452561-2abe9e80-ea8b-11e9-8811-eaf58819118c.png)
У тебя же интервал для чего тут вот эта проверка?
![Screenshot 2019-10-09 at 11 52 51](https://user-images.githubusercontent.com/31854808/66452610-5f325a80-ea8b-11e9-9d2b-05c3b4881c57.png)
Этот метод нигде не переиспользуется зачем его отдельно выносить? 
![Screenshot 2019-10-09 at 11 59 55](https://user-images.githubusercontent.com/31854808/66452884-7cb3f400-ea8c-11e9-80ce-73193fa105f8.png)
Для чего нужен этот метод? 
![Screenshot 2019-10-09 at 12 02 11](https://user-images.githubusercontent.com/31854808/66452946-b422a080-ea8c-11e9-86e0-f11bbb07849b.png)

**Comment by KatePronina** [comment]
> Этот метод нигде не переиспользуется зачем его отдельно выносить?

Увлеклась разбивкой на отдельные методы)

**Comment by KatePronina** [comment]
> Для чего нужен этот метод?

В случае, когда у слайдера два значения, и происходит клик по шкале или пользователь решит изменить значение через метод js, но передаст только одно число, нужно определить, какое значение из двух нужно менять
Этот метод (`defineIfValueIsEnd`) определяет, к какому текущему значению(начальному или конечному) ближе новое значение из шкалы или настроек

**Comment by KatePronina** [comment]
> Для чего нужны вот эти проверки?

Без проверки будет так:
![cgnyTZZ_S1U](https://user-images.githubusercontent.com/25391680/66480221-c8739700-eaa6-11e9-8d81-d7254e1e1116.jpg)

`if (eventType === 'positionPercentUpdated' && settings.positionPercent)`
Когда приходит новая позиция от вью, нужно сначала посчитать значение от нее, чтобы было что проверять

`if (typeof settings.value === 'undefined')`
Это если при инициализации слайдера в настройки не было передано никакое значение, то его нужно создать

**Comment by KatePronina** [comment]
> У тебя же интервал для чего тут вот эта проверка?
> ```
> 
> if (typeof settings.value === 'number') {
>    return this.makeIntervalValueFromNumber(settings);
> }
> 
> ```

Интервал по типу слайдера, но значение в него может приходить не только в виде массива из двух чисел, но и просто в виде числа
Такая ситуация происходит
- когда передвигается один ползунок из двух (значение приходит вместе с указанием какое оно - большее или меньшее)
- когда приходит значение по клику на шкалу
- в случае, если пользователь решит изменить для интервального слайдера значение и передаст одно число, это не приведет к ошибке, модель сама определит какое это будет значение

Получается, название метода `validateIntervalValue` не совсем корректно передает его суть, я исправлю

**Comment by Sha1fei** [comment]
> В случае, когда у слайдера два значения, и происходит клик по шкале или пользователь решит изменить значение через метод js, но передаст только одно число, нужно определить, какое значение из двух нужно менять
> Этот метод (`defineIfValueIsEnd`) определяет, к какому текущему значению(начальному или конечному) ближе новое значение из шкалы или настроек

  Давай руководствоваться принципом - необходимой достаточностью) У тебя сейчас очень много напилено, давай уберем что не предусмотрено заданием, и не противоречит  UI. Этот метод точно из их числа, нам не нужно обрабатывать клик по шкале, а тайпскрипт позволяет затипизировать, что передать нужно два значения к примеру, это можно опять же если будет необходимость реализовать кортежами.

**Comment by Sha1fei** [comment]
> `if (typeof settings.value === 'undefined')`
> Это если при инициализации слайдера в настройки не было передано никакое значение, то его нужно создать

У тебя зашиты в слайдере инициализуемые параметры, не нужно дублирования)

**Comment by Sha1fei** [comment]
> `if (eventType === 'positionPercentUpdated' && settings.positionPercent)`
> Когда приходит новая позиция от вью, нужно сначала посчитать значение от нее, чтобы было что проверять

Я к тому что она делает в validateValue, значение и валидируешь его пусть это вызывается внутри validateRangeSliderValue. По итогу у тебя буде прозрачная структура. По типу слайдера  можно будет реализовать  switch, а дефолтным будет settings.value.

**Comment by Sha1fei** [comment]
> * когда передвигается один ползунок из двух (значение приходит вместе с указанием какое оно - большее или меньшее)

Давай не будем усложнять, в проекте еще полно мест где придется накрутить логики. Про последние два я уже писал пункта, а про этот, ты можешь сделать два интерфейса IRangeSliderValue IIntervalSliderValue, у которых разные .type и разные поле value
![Снимок экрана от 2019-10-10 22-44-26](https://user-images.githubusercontent.com/31854808/66584541-8bdf9280-ebaf-11e9-99e0-811f83256251.png)
![Снимок экрана от 2019-10-10 22-40-18](https://user-images.githubusercontent.com/31854808/66584568-9437cd80-ebaf-11e9-8973-9eda34cdf49e.png)

**Comment by KatePronina** [comment]
Если задать `validateValues = (settings: IValidateRangeValue | IValidateIntervalValue)`
и передать в validate values объект с типом `value: number | number[]` , ts все равно ругается

![](https://sun9-27.userapi.com/c851124/v851124175/1e2819/55hPvbx4MnI.jpg)


![](https://sun9-12.userapi.com/c855532/v855532175/125ba5/-xtyxV3MVX8.jpg)


Даже с проверкой на тип value ругается

![](https://sun9-9.userapi.com/c857336/v857336175/3297/BeQ1GXtN1dU.jpg)

Теперь для интервального слайдера во всех случаях приходит только массив с одним или двумя значениями
Но с интерфейсами пока не вышло, попробую что-нибудь придумать

**Comment by KatePronina** [comment]
Придумала, пока только так получилось решить

**Comment by Sha1fei** [comment]
Это решается с помощью Type Guards https://www.typescriptlang.org/docs/handbook/advanced-types.html#type-guards-and-differentiating-types Ты можешь либо 1) написать функцию которая аналогична этой https://www.typescriptlang.org/docs/handbook/advanced-types.html#using-type-predicates она уточнит твой тип с помощью is, и положить его в if, njulf ензуыскшзе поймет какой из двух типов ты используешь) Либо, что попроще использовать switch который я приводил выше, для поля type в settings задать конкретные строковые значения. Когда ты пробегаешь свичом и сравниваешь на соответствие значение поля и константы, тайпскрипт тоже понимает какой типы ты используешь) И как следствие поймет, что у тебя должно лежать в value значение или массив значений)

**Comment by Sha1fei** [comment]
Решить каким способом сужать тип, это остается на твое усмотрение, но метод validateState тогда стоит оптимизировать, 
![Снимок экрана от 2019-10-15 16-28-01](https://user-images.githubusercontent.com/31854808/66819205-c8710c80-ef68-11e9-8c4a-b6af9728fe5c.png)

не забывай про десткрутуризацию, лишние проверки нужно либо удалить или они должны уйти внутрь методов валидации 
![Снимок экрана от 2019-10-15 15-14-51](https://user-images.githubusercontent.com/31854808/66819148-a5def380-ef68-11e9-8939-47e3e1a0ec40.png)

**Comment by Sha1fei** [comment]
Давай переименуем этот метод isValueTypeEnd в  isSecondValueChange, а так в целом по модели думаю все)

**Comment by KatePronina** [comment]
Подумала над тем, как объединить методы
``` js
 this.view.subscribe(this.stateChanged, 'valueUpdated'); // это было для клика по шкале
 this.view.subscribe(this.positionPercentUpdated, 'positionPercentUpdated'); 
```

В итоге решила с другой стороны: вместо того, чтобы передавать при клике на шкалу positionPercent - т.е. заменить оба метода одним `positionPercentUpdated`, я заменила оба метода методом  `updateState`
Методы `positionPercentUpdated` и `stateChanged` по сути делали одно: подтягивали текущий стейт из модели, добавляли в него новые изменившиеся параметры, отправляли новый стейт в модель
Теперь это все делает один метод `updateState`
