### ISSUE TITLE
Разделяй стили блоков по отдельным файлам

### ISSUE THREAD

**Issue by Sha1fei** [KatePronina/Slider#20]
![Снимок экрана от 2019-08-26 16-56-31](https://user-images.githubusercontent.com/31854808/63682605-82c67c00-c822-11e9-8e1d-87ee023ffa99.png)

**Comment by Sha1fei** [comment]
Убери у блока .configuration внешнее позиционирование)

**Comment by Sha1fei** [comment]
Не до конца подправила
![Снимок экрана от 2019-09-02 17-16-11](https://user-images.githubusercontent.com/31854808/64107765-75227080-cda5-11e9-88a9-fa14365a9665.png)

**Comment by Sha1fei** [comment]
Мы обычно для тегов html body заводи отдельный файл base.scss

**Comment by KatePronina** [comment]
Переделала, там пока что класс `slider-section__configuration` добавляется напрямую в js, я это исправлю, когда буду выносить configuration из слайдера в ишью про архитектуру
