### ISSUE TITLE
Пофиксить ошибки при сборке

### ISSUE THREAD

**Issue by Sha1fei** [KatePronina/Slider#21]
![Снимок экрана от 2019-09-05 14-02-31](https://user-images.githubusercontent.com/31854808/64319152-e2244900-cfe5-11e9-8027-66c9e40ef38f.png)

**Comment by KatePronina** [comment]
Тут немного сложно, т.к. мне ts не выдает эти ошибки, и проект успешно собирается
![OpsVIKoP760](https://user-images.githubusercontent.com/25391680/64559433-f56d4680-d34e-11e9-9c57-7be994881003.jpg)
Я так поняла, что проблема только с наследуемыми свойствами/методами
Попыталась это как-то исправить, но не знаю, в правильном ли направлении я смотрю?

**Comment by Sha1fei** [comment]
Нет, проблема в том, что у тебя система регистронезависимая система (на маках такая проблема втречается часто) переименуй начало именований файлов с верхнего регистра (также как в импортах указываешь) и заработает у всех)
![Снимок экрана от 2019-09-10 17-52-56](https://user-images.githubusercontent.com/31854808/64608208-58fd7f80-d3f4-11e9-851f-ad1789646a67.png)

**Comment by KatePronina** [comment]
Ааа, поняла, спасибо)

**Comment by Sha1fei** [comment]
Еще нужно здесь изменить регистр
![Снимок экрана от 2019-09-11 09-16-41](https://user-images.githubusercontent.com/31854808/64663115-f3050c80-d474-11e9-817e-8ad4312f9279.png)
