### ISSUE TITLE
Использовать шаблонизаторы для создания верстки

### ISSUE THREAD

**Issue by Sha1fei** [KatePronina/Slider#4]
https://habr.com/ru/post/219873/

**Comment by Sha1fei** [comment]
Используй преимущества шаблонизатора) Не дублируй повторяющийся код)

**Comment by Sha1fei** [comment]
Здесь не подправила
![Снимок экрана от 2019-09-11 09-27-58](https://user-images.githubusercontent.com/31854808/64663597-97d41980-d476-11e9-9200-ffd666a5a753.png)
![Снимок экрана от 2019-09-11 09-28-05](https://user-images.githubusercontent.com/31854808/64663599-97d41980-d476-11e9-92a9-533053de8b00.png)

**Comment by Sha1fei** [comment]
Здесь тоже нужно убрать дублирование
![Снимок экрана от 2019-09-13 12-01-25](https://user-images.githubusercontent.com/31854808/64838735-bffe7c80-d61e-11e9-83a1-5c3b8d88d5f8.png)

**Comment by Sha1fei** [comment]
![Screenshot 2019-09-19 at 13 48 54](https://user-images.githubusercontent.com/31854808/65220518-10754e80-dae5-11e9-81e9-e074c76b4605.png) 
Удали heigth пусть высота будет определяться по контенту

**Comment by KatePronina** [comment]
Это обертка для слайдера, я задала ей высоту, чтобы при вертикальном расположении слайдер подстраивался под высоту этой обертки, т.к. своей высоты у слайдера нет, он подстраивается под родителя

**Comment by Sha1fei** [comment]
Тогда можно задать модификатор для slider-section__slider и для _direction_vertical  задавать высоту, так будет лучше смотреться)
