### ISSUE TITLE
Убрать as из проекта при типизации

### ISSUE THREAD

**Issue by Sha1fei** [KatePronina/Slider#6]
В стажерском задании они не нужны)

**Comment by KatePronina** [comment]
Т.е. переписать `this.barDOMElement as HTMLElement` на `<HTMLElement>this.barDOMElement` ?

**Comment by Sha1fei** [comment]
Нет, это ведь одно и тоже почти) нужно типизировать  поля при их объявлении, а если поле может быть  null то делать проверки (либо в if(){}   либо можно использовать  &&). 

![Снимок экрана от 2019-09-02 18-03-46](https://user-images.githubusercontent.com/31854808/64110339-157b9380-cdac-11e9-926e-60b14bff2706.png)
